language: go
go: "1.10"

services:
- docker

install: true
script:
- make docker-build

deploy:
- provider: script
  script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
  - make docker-build docker-push
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
  - IMAGE_TAG=$TRAVIS_TAG make docker-build docker-push
  skip_cleanup: true
  on:
    tags: true
