apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cluster-network-addons-operator.0.86.0
  namespace: placeholder
  annotations:
    capabilities: "Full Lifecycle"
    categories: "Networking"
    alm-examples: |
      [
        {
          "apiVersion":"networkaddonsoperator.network.kubevirt.io/v1",
          "kind":"NetworkAddonsConfig",
          "metadata": {
            "name":"cluster"
          },
          "spec": {
            "multus":{},
            "linuxBridge":{},
            "kubeMacPool": {
              "rangeStart": "02:00:00:00:00:00",
              "rangeEnd": "FD:FF:FF:FF:FF:FF"
            },
            "ovs": {},
            "macvtap": {},
            "imagePullPolicy": "IfNotPresent"
          }
        }
      ]
    description: Additional networking components for Kubernetes
spec:
  displayName: Cluster Network Addons
  description: Deploy additional networking components for Kubernetes
  keywords:
    - Networking
    - Multus
    - CNI
    - macpool
    - SR-IOV
    - Bridge
    - KubeVirt
    - Virtualization
  version: 0.86.0
  minKubeVersion: 1.10.0
  maturity: alpha

  replaces: cluster-network-addons-operator.0.85.0

  maintainers:
    - name: KubeVirt project
      email: kubevirt-dev@googlegroups.com
  provider:
    name: KubeVirt project
  links:
    - name: Cluster Network Addons Operator
      url: https://github.com/kubevirt/cluster-network-addons-operator
  icon: []
  labels:
    alm-owner-kubevirt: cluster-network-addons
    operated-by: cluster-network-addons
  selector:
    matchLabels:
      alm-owner-kubevirt: cluster-network-addons
      operated-by: cluster-network-addons
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: cluster-network-addons-operator
          rules:
            - apiGroups:
              - ""
              resources:
              - pods
              - configmaps
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              - delete
            - apiGroups:
              - apps
              resources:
              - deployments
              - replicasets
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              - delete

      clusterPermissions:
        - serviceAccountName: cluster-network-addons-operator
          rules:
            - apiGroups:
              - security.openshift.io
              resourceNames:
              - privileged
              resources:
              - securitycontextconstraints
              verbs:
              - get
              - list
              - watch
              - use
            - apiGroups:
              - operator.openshift.io
              resources:
              - networks
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - networkaddonsoperator.network.kubevirt.io
              resources:
              - networkaddonsconfigs
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - '*'
              resources:
              - '*'
              verbs:
              - '*'

      deployments:
        - name: cluster-network-addons-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: cluster-network-addons-operator
            strategy:
              type: Recreate
            template:
              metadata:
                annotations:
                  description: cluster-network-addons-operator manages the lifecycle of different
                    Kubernetes network components on top of Kubernetes cluster
                labels:
                  name: cluster-network-addons-operator
                  prometheus.cnao.io: "true"
              spec:
                containers:
                - env:
                  - name: MULTUS_IMAGE
                    value: ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:4e336bd177b5c60e753be48484abb48edb002c7207de9f265fff2e00e8f5106e
                  - name: MULTUS_DYNAMIC_NETWORKS_CONTROLLER_IMAGE
                    value: ghcr.io/k8snetworkplumbingwg/multus-dynamic-networks-controller@sha256:ef8fe97a52eb9b3c03e99979a42cf2edaa7b3365cb3eb4dd1654b1bb9e73d7a3
                  - name: LINUX_BRIDGE_IMAGE
                    value: quay.io/kubevirt/cni-default-plugins@sha256:e75d67fb44f4b748137c85b1c06b500607410a3218cafbf8a4bb6359f2b90373
                  - name: LINUX_BRIDGE_MARKER_IMAGE
                    value: quay.io/kubevirt/bridge-marker@sha256:5d24c6d1ecb0556896b7b81c7e5260b54173858425777b7a84df8a706c07e6d2
                  - name: OVS_CNI_IMAGE
                    value: quay.io/kubevirt/ovs-cni-plugin@sha256:5f7290e2294255ab2547c3b4bf48cc2d75531ec5a43e600366e9b2719bef983f
                  - name: KUBEMACPOOL_IMAGE
                    value: quay.io/kubevirt/kubemacpool@sha256:0cc5ad824fc163d6dea5e9bd872467c691eaa9a88944008b5d746495b2a72214
                  - name: MACVTAP_CNI_IMAGE
                    value: quay.io/kubevirt/macvtap-cni@sha256:434420511e09b2b5ede785a2c9062b6658ffbc26fbdd4629ce06110f9039c600
                  - name: KUBE_RBAC_PROXY_IMAGE
                    value: quay.io/openshift/origin-kube-rbac-proxy@sha256:baedb268ac66456018fb30af395bb3d69af5fff3252ff5d549f0231b1ebb6901
                  - name: KUBE_SECONDARY_DNS_IMAGE
                    value: ghcr.io/kubevirt/kubesecondarydns@sha256:b489a7c5d05b000f776c9c302985b8b7f29ff31f577a1480912ed625c8772d6b
                  - name: CORE_DNS_IMAGE
                    value: k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e
                  - name: OPERATOR_IMAGE
                    value: quay.io/kubevirt/cluster-network-addons-operator:v0.86.0
                  - name: OPERATOR_NAME
                    value: cluster-network-addons-operator
                  - name: OPERATOR_VERSION
                    value: 0.86.0
                  - name: OPERATOR_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: OPERAND_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: WATCH_NAMESPACE
                  - name: MONITORING_NAMESPACE
                    value: openshift-monitoring
                  - name: MONITORING_SERVICE_ACCOUNT
                    value: prometheus-k8s
                  image: quay.io/kubevirt/cluster-network-addons-operator:v0.86.0
                  imagePullPolicy: Always
                  name: cluster-network-addons-operator
                  resources:
                    requests:
                      cpu: 50m
                      memory: 30Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                      - ALL
                - args:
                  - --logtostderr
                  - --secure-listen-address=:8443
                  - --upstream=http://127.0.0.1:8080
                  image: quay.io/openshift/origin-kube-rbac-proxy@sha256:baedb268ac66456018fb30af395bb3d69af5fff3252ff5d549f0231b1ebb6901
                  imagePullPolicy: Always
                  name: kube-rbac-proxy
                  ports:
                  - containerPort: 8443
                    name: metrics
                    protocol: TCP
                  resources:
                    requests:
                      cpu: 10m
                      memory: 20Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                      - ALL
                  terminationMessagePolicy: FallbackToLogsOnError
                priorityClassName: system-cluster-critical
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: cluster-network-addons-operator

  relatedImages:
    - image: "ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:4e336bd177b5c60e753be48484abb48edb002c7207de9f265fff2e00e8f5106e"
      name: "multus-cni"
    - image: "ghcr.io/k8snetworkplumbingwg/multus-dynamic-networks-controller@sha256:ef8fe97a52eb9b3c03e99979a42cf2edaa7b3365cb3eb4dd1654b1bb9e73d7a3"
      name: "multus-dynamic-networks-controller"
    - image: "quay.io/kubevirt/cni-default-plugins@sha256:e75d67fb44f4b748137c85b1c06b500607410a3218cafbf8a4bb6359f2b90373"
      name: "cni-default-plugins"
    - image: "quay.io/kubevirt/bridge-marker@sha256:5d24c6d1ecb0556896b7b81c7e5260b54173858425777b7a84df8a706c07e6d2"
      name: "bridge-marker"
    - image: "quay.io/kubevirt/kubemacpool@sha256:0cc5ad824fc163d6dea5e9bd872467c691eaa9a88944008b5d746495b2a72214"
      name: "kubemacpool"
    - image: "quay.io/kubevirt/ovs-cni-plugin@sha256:5f7290e2294255ab2547c3b4bf48cc2d75531ec5a43e600366e9b2719bef983f"
      name: "ovs-cni-plugin"
    - image: "quay.io/kubevirt/macvtap-cni@sha256:434420511e09b2b5ede785a2c9062b6658ffbc26fbdd4629ce06110f9039c600"
      name: "macvtap-cni"
    - image: "quay.io/openshift/origin-kube-rbac-proxy@sha256:baedb268ac66456018fb30af395bb3d69af5fff3252ff5d549f0231b1ebb6901"
      name: "origin-kube-rbac-proxy"
    - image: "ghcr.io/kubevirt/kubesecondarydns@sha256:b489a7c5d05b000f776c9c302985b8b7f29ff31f577a1480912ed625c8772d6b"
      name: "kubesecondarydns"
    - image: "k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e"
      name: "coredns"
    - image: "quay.io/kubevirt/cluster-network-addons-operator:v0.86.0"
      name: "cluster-network-addons-operator"
  customresourcedefinitions:
    owned:
      - name: networkaddonsconfigs.networkaddonsoperator.network.kubevirt.io
        version: v1
        group: networkaddonsoperator.network.kubevirt.io
        kind: NetworkAddonsConfig
        displayName: Cluster Network Addons
        description: Cluster Network Addons
