apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-network-addons-operator
  namespace: cluster-network-addons-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-network-addons-operator
  template:
    metadata:
      labels:
        name: cluster-network-addons-operator
    spec:
      hostNetwork: true
      serviceAccountName: cluster-network-addons-operator
      containers:
        - name: cluster-network-addons-operator
          # Replace this with the built image name
          image: quay.io/phoracek/cluster-network-addons-operator
          command:
          - cluster-network-addons-operator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          env:
            - name: IMAGE_PULL_POLICY
              value: "Always"
            - name: MULTUS_IMAGE
              value: "docker.io/nfvpe/multus:latest"
            - name: LINUX_BRIDGE_IMAGE
              value: "quay.io/kubevirt/cni-default-plugins"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-network-addons-operator"
