apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cluster-network-addons-operator.0.52.0
  namespace: placeholder
  annotations:
    capabilities: "Full Lifecycle"
    categories: "Networking"
    alm-examples: |
      [
        {
          "apiVersion":"networkaddonsoperator.network.kubevirt.io/v1",
          "kind":"NetworkAddonsConfig",
          "metadata": {
            "name":"cluster"
          },
          "spec": {
            "multus":{},
            "linuxBridge":{},
            "kubeMacPool": {
              "rangeStart": "02:00:00:00:00:00",
              "rangeEnd": "FD:FF:FF:FF:FF:FF"
            },
            "nmstate":{},
            "ovs": {},
            "macvtap": {},
            "imagePullPolicy": "IfNotPresent"
          }
        }
      ]
    description: Additional networking components for Kubernetes
spec:
  displayName: Cluster Network Addons
  description: Deploy additional networking components for Kubernetes
  keywords:
    - Networking
    - Multus
    - CNI
    - macpool
    - SR-IOV
    - Bridge
    - nmstate
    - KubeVirt
    - Virtualization
  version: 0.52.0
  minKubeVersion: 1.10.0
  maturity: alpha

  replaces: cluster-network-addons-operator.0.51.0

  maintainers:
    - name: KubeVirt project
      email: kubevirt-dev@googlegroups.com
  provider:
    name: KubeVirt project
  links:
    - name: Cluster Network Addons Operator
      url: https://github.com/kubevirt/cluster-network-addons-operator
  icon: []
  labels:
    alm-owner-kubevirt: cluster-network-addons
    operated-by: cluster-network-addons
  selector:
    matchLabels:
      alm-owner-kubevirt: cluster-network-addons
      operated-by: cluster-network-addons
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: cluster-network-addons-operator
          rules:
            - apiGroups:
              - ""
              resources:
              - pods
              - configmaps
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              - delete
            - apiGroups:
              - apps
              resources:
              - deployments
              - replicasets
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              - delete

      clusterPermissions:
        - serviceAccountName: cluster-network-addons-operator
          rules:
            - apiGroups:
              - security.openshift.io
              resourceNames:
              - privileged
              resources:
              - securitycontextconstraints
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - operator.openshift.io
              resources:
              - networks
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - networkaddonsoperator.network.kubevirt.io
              resources:
              - networkaddonsconfigs
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - '*'
              resources:
              - '*'
              verbs:
              - '*'

      deployments:
        - name: cluster-network-addons-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: cluster-network-addons-operator
            strategy:
              type: Recreate
            template:
              metadata:
                annotations:
                  description: cluster-network-addons-operator manages the lifecycle of different
                    Kubernetes network components on top of Kubernetes cluster
                labels:
                  name: cluster-network-addons-operator
              spec:
                containers:
                - env:
                  - name: MULTUS_IMAGE
                    value: quay.io/kubevirt/cluster-network-addon-multus@sha256:32867c73cda4d605651b898dc85fea67d93191c47f27e1ad9e9f2b9041c518de
                  - name: LINUX_BRIDGE_IMAGE
                    value: quay.io/kubevirt/cni-default-plugins@sha256:a90902cf3e5154424148bf3ba3c1bf90316cc77a54042cf6584fe8aedbe6daec
                  - name: LINUX_BRIDGE_MARKER_IMAGE
                    value: quay.io/kubevirt/bridge-marker@sha256:799459f8509a06ea643aa2f6ac02826721a641333aacab07e53166139a5a66c3
                  - name: NMSTATE_HANDLER_IMAGE
                    value: quay.io/nmstate/kubernetes-nmstate-handler@sha256:4457684e803aebbdb1843de45494af9bc284fa1ad2eb64263bc70036301ddf36
                  - name: OVS_CNI_IMAGE
                    value: quay.io/kubevirt/ovs-cni-plugin@sha256:9ea002a51fd6cd706064a13e4eb79618e286f31be291ea4485de92675f26daa1
                  - name: OVS_MARKER_IMAGE
                    value: quay.io/kubevirt/ovs-cni-marker@sha256:dca0d0432eacb1e97ea49c755df1c232159fe4267e7f872222ef0ef77e3d8915
                  - name: KUBEMACPOOL_IMAGE
                    value: quay.io/kubevirt/kubemacpool@sha256:9f04a0b958d744c043535e024d3647113a72ec73e399682ceee3f1a1228c3435
                  - name: MACVTAP_CNI_IMAGE
                    value: quay.io/kubevirt/macvtap-cni@sha256:f20d5e56f8b8c1ab7e5a64e536b66f65aa688b2d1dc0b37e3c26c2af2b481266
                  - name: OPERATOR_IMAGE
                    value: quay.io/kubevirt/cluster-network-addons-operator:v0.52.0
                  - name: OPERATOR_NAME
                    value: cluster-network-addons-operator
                  - name: OPERATOR_VERSION
                    value: 0.52.0
                  - name: OPERATOR_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: OPERAND_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: WATCH_NAMESPACE
                  image: quay.io/kubevirt/cluster-network-addons-operator:v0.52.0
                  imagePullPolicy: Always
                  name: cluster-network-addons-operator
                  resources: {}
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: cluster-network-addons-operator

  relatedImages:
    - image: "quay.io/kubevirt/cluster-network-addon-multus@sha256:32867c73cda4d605651b898dc85fea67d93191c47f27e1ad9e9f2b9041c518de"
      name: "cluster-network-addon-multus"
    - image: "quay.io/kubevirt/cni-default-plugins@sha256:a90902cf3e5154424148bf3ba3c1bf90316cc77a54042cf6584fe8aedbe6daec"
      name: "cni-default-plugins"
    - image: "quay.io/kubevirt/bridge-marker@sha256:799459f8509a06ea643aa2f6ac02826721a641333aacab07e53166139a5a66c3"
      name: "bridge-marker"
    - image: "quay.io/kubevirt/kubemacpool@sha256:9f04a0b958d744c043535e024d3647113a72ec73e399682ceee3f1a1228c3435"
      name: "kubemacpool"
    - image: "quay.io/nmstate/kubernetes-nmstate-handler@sha256:4457684e803aebbdb1843de45494af9bc284fa1ad2eb64263bc70036301ddf36"
      name: "kubernetes-nmstate-handler"
    - image: "quay.io/kubevirt/ovs-cni-plugin@sha256:9ea002a51fd6cd706064a13e4eb79618e286f31be291ea4485de92675f26daa1"
      name: "ovs-cni-plugin"
    - image: "quay.io/kubevirt/ovs-cni-marker@sha256:dca0d0432eacb1e97ea49c755df1c232159fe4267e7f872222ef0ef77e3d8915"
      name: "ovs-cni-marker"
    - image: "quay.io/kubevirt/macvtap-cni@sha256:f20d5e56f8b8c1ab7e5a64e536b66f65aa688b2d1dc0b37e3c26c2af2b481266"
      name: "macvtap-cni"
    - image: "quay.io/kubevirt/cluster-network-addons-operator:v0.52.0"
      name: "cluster-network-addons-operator"
  customresourcedefinitions:
    owned:
      - name: networkaddonsconfigs.networkaddonsoperator.network.kubevirt.io
        version: v1
        group: networkaddonsoperator.network.kubevirt.io
        kind: NetworkAddonsConfig
        displayName: Cluster Network Addons
        description: Cluster Network Addons
